apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Configure performance profile. For OCP 4.12 and below, this PAO Operataor
- pao.yaml

# TuneD Operator for systemctl configs
- tuned.yaml

# Machine config
- mc.yaml

#Sets up the namespace for XRd
- ns.yaml

# Create a service account and Role Based Access for the account
- sa.yaml
- role.yaml

# Contain startup configuration for XRd - Currently, only a username
- configmap.yaml

# Stateful set to deploy XRd application
- nad.yaml

# Stateful set to deploy XRd application
- statefulset.yaml
