apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Change this namespace value if you want to use a different one than the default
namespace: xrd 

resources:
# Configure performance profile. For OCP 4.12 and below, this PAO Operataor
- pao.yaml

# TuneD Operator for systemctl configs
- tuned.yaml

# Machine config
- mc.yaml

#Sets up the namespace for XRd
- ns.yaml

# Create a service account and Role Based Access for the account
- sa.yaml
- role.yaml

# Contain startup configuration for XRd - Currently, only a username
- configmap.yaml

# Stateful set to deploy XRd application
- nad.yaml

# Stateful set to deploy XRd application
- statefulset.yaml
# alternative to the "statefulset", if desired then "deloymentset" can be used as follows: 
# - deployment.yaml
# note: There is a slight difference in how the resulting pods are named based on what CR is used. When using "Deoployment" , 
# the name of pod is something like "xrd-control-plane-6cb7945687-9t7w4" while with statefuset  
# deployed pods will be named like "xrd-control-plane-0" 
