apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-1
  namespace: xrd
spec:
  config: '{ "cniVersion": "0.3.1", "name": "macvlan-1", "type": "macvlan", "mode": "bridge", "ipam": { }}'
    # For external connection, add interface using -->  "master": "eno2"
