apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: iosxr-performanceprofile
spec:
  additionalKernelArgs:
  cpu:
    isolated: 4-31
    reserved: 0-3
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 2
        size: 1G
  nodeSelector:
    node-role.kubernetes.io/master: ""
  realTimeKernel:
    enabled: false
